name: Go package

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose up -d --build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          cache: true

      - name: Install dependencies
        run: |
          go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Stop containers
        if: always()
        run: docker-compose down